kind: Deployment
apiVersion: apps/v1
metadata:
   name: nginx3
   namespace: my-app-ns
   labels:
      app: my-app

spec: 
  replicas: 3
  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
     app: my-app

  spec:
    containers:
    - name:  nginx
      image:  registry/user/image
    ports:
    - containerPort: 80
    
